name: Build Docker Image

on:
  push:
    branches:
      - '*'
    tags:
      - 'v*'

permissions:
  packages: write
  contents: read

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: GHCR-Action
        uses: KuhlTime/ghcr-action@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}