name: Build Docker Image

on:
  push:
    branches:
      - '*'
    tags:
      - 'v*'
  workflow_dispatch:

      
permissions:
  packages: write
  contents: read

jobs:
  # docker:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: GHCR-Action
  #       uses: KuhlTime/ghcr-action@v2
  #       with:
  #         token: ${{ secrets.GITHUB_TOKEN }}
  ghcr:
    runs-on: ubuntu-latest
    steps:
      - name: Build and Push Container to ghcr.io
        uses: GlueOps/github-actions-build-push-containers@v0.4.1
