name: Linter

on:
  # push:
  #   branches-ignore: [main]
  pull_request:
    branches: [main]
    paths-ignore:
      - '**.md'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  linter:
    name: Linter
    runs-on: [ubuntu-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Lint code
        uses: github/super-linter@v6
        env:
          VALIDATE_ALL_CODEBASE: false
          VALIDATE_JAVASCRIPT_ES: true
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
