name: Publish

on:
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'
  pull_request:
    paths-ignore:
      - '**.md'
  workflow_dispatch:

jobs:
  build:
    name: Build

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Node 20
      uses: actions/setup-node@v4
      with:
        node-version: 20.12
        cache: 'npm'

    - name: Install dependencies
      run: |
        npm ci

    - name: Compile
      run: |
        npm run clean && \
        npm run dist

    - uses: actions/upload-artifact@v4
      with:
        # Name of the artifact to upload.
        # Optional. Default is 'artifact'
        name: "app-${{ github.ref_name }}"
    
        # A file, directory or wildcard pattern that describes what to upload
        # Required.
        path: dist/*.js