name: Release
permissions:
  contents: write
on:
  # release:
  #   types: [created]
  push:
    branches:
      - main
    tags:
      - v[0-9]+.*
    paths-ignore:
      - '**.md'
  pull_request:
    paths-ignore:
      - '**.md'
jobs:
  build:
    name: Build
    # needs: run-linters
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Setup Node 16
      uses: actions/setup-node@v4
      with:
        node-version: 16
        cache: 'npm'
    - name: Install dependencies
      run: |
        npm ci
    - name: Compile
      run: |
        npm run clean && \
        npm run dist
    - name: Create artifact
      uses: actions/upload-artifact@v4
      with:
        name: "app-${{ github.sha }}"
        path: dist/*.js
  create-release:
    name: Create release
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: taiki-e/create-gh-release-action@v1
        with:
          changelog: CHANGELOG.md
          token: ${{ secrets.GITHUB_TOKEN }}
          draft: true
          title: $version
          branch: main
          tag: $tag
