name: Tag Release
on:
  workflow_dispatch:

permissions:
  contents: write
  packages: write
  discussions: write

jobs:
  generate_release:
    name: Release
    #if: contains(github.event.pull_request.head.ref, 'release/v') && github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Fetch version
        run: |
          VERSION=$(echo "${GITHUB_HEAD_REF}" | sed "s/release\\/v//")
          echo "version=${VERSION}" >> $GITHUB_OUTPUT
        id: fetch-version

      - name: Generate release notes
        uses: softprops/action-gh-release@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag_name: v${{ steps.fetch-version.outputs.version }}
          generate_release_notes: true